#!/bin/bash

REPONAME=lib-processor
TMP_FILE=$REPONAME.raw
cat /dev/null > $TMP_FILE
cat - > $TMP_FILE

### don't remember chmod 664 $STATUS_FILE and chown jenkins:git $STATUS_FILE
STATUS_FILE=/home/jenkins/irls-reader-artifacts/$REPONAME-status.json
# create status of repo json file
cat /dev/null > $STATUS_FILE
echo '{' >> $STATUS_FILE
echo -e '\t"processorBranch": [' >> $STATUS_FILE
counter=1
a=$(git branch -a | sed 's/\*//g' | wc -l)
for i in $(git branch -a | sed 's/\*//g'); do
        HASHCOMMIT=$(git log -1 "$i" --pretty=format:%H)
        if [ "$counter" -eq "$a" ]
        then
                echo -e '\t\t{ "branchName":"'$i'", "hashCommit":"'$HASHCOMMIT'"}' >> $STATUS_FILE
                ((counter++))
        else
                echo -e '\t\t{ "branchName":"'$i'", "hashCommit":"'$HASHCOMMIT'" },' >> $STATUS_FILE
                ((counter++))
        fi
done
echo -e '\t]' >> $STATUS_FILE
echo '}'  >> $STATUS_FILE


BRANCH=$(cat $TMP_FILE | awk '{print $3}' | sed 's/refs\/heads\///g')
# inner variables of jenkins - GIT_URL and GIT_COMMIT
# determine variables for meta json
CURRENT_CODE_PATH=/home/jenkins/irls-$REPONAME-deploy
GIT_COMMIT=$(git show $BRANCH -s --format=%H)
META=$REPONAME-meta.json
COMMIT_URL="http://wpp.isd.dp.ua/gitlab/irls/$REPONAME/commit/$GIT_COMMIT"
COMMIT_MESSAGE=$(git show $BRANCH -s --format=%s | sed 's@"@@g')
COMMIT_DATE=$(git show $BRANCH -s --format=%ci)
COMMIT_AUTHOR=$(git show $BRANCH -s --format=%cn)
EMAIL=$(git show -s $BRANCH --format=%ce)

# run of job
wget -qO- --auth-no-challenge --http-user=dvac --http-password="0f64d6238d107249f79deda4d6a2f9fc" http://wpp.isd.dp.ua/jenkins/job/irls-prebuild/buildWithParameters\?token=Sheedah8\&REPONAME=$REPONAME\&BRANCH=$BRANCH &> /dev/null
wget -qO- --auth-no-challenge --http-user=dvac --http-password="0f64d6238d107249f79deda4d6a2f9fc" http://wpp.isd.dp.ua/jenkins/job/lib-processor-build/buildWithParameters\?token=Sheedah8\&PROCESSOR_BRANCHNAME=$BRANCH\&PROCESSOR_CURRENT_CODE_PATH=$CURRENT_CODE_PATH\&PROCESSOR_HASHCOMMIT=$GIT_COMMIT\&PROCESSOR_META=$META\&COMMIT_URL=$COMMIT_URL\&COMMIT_MESSAGE="$COMMIT_MESSAGE"\&COMMIT_DATE="$COMMIT_DATE"\&COMMIT_AUTHOR="$COMMIT_AUTHOR"\&EMAIL="$EMAIL" &> /dev/null
# email notify
cat $TMP_FILE | git-commit-notifier /usr/local/lib/ruby/gems/2.1.0/gems/git-commit-notifier-0.12.6/config/git-notifier-config
