#!/bin/bash

TMP_FILE=testraw
cat /dev/null > $TMP_FILE
cat - > $TMP_FILE

#REPONAME=targets
BRANCH=$(cat $TMP_FILE | awk '{print $3}' | sed 's/refs\/heads\///g')

# run of job
#wget -qO- --auth-no-challenge --http-user=dvac --http-password="0f64d6238d107249f79deda4d6a2f9fc" http://wpp.isd.dp.ua/jenkins/job/irls-prebuild/buildWithParameters\?token=Sheedah8\&REPONAME=$REPONAME\&BRANCH=$BRANCH &> /dev/null

# refresh list of targets
TMP_LIST_FILE=templistfile
cat /dev/null > $TMP_LIST_FILE
FILE=/home/jenkins/irls-reader-artifacts/newtargets.json
list_of_targets=($(git ls-tree --name-only -d $BRANCH))
project_id=$(curl -H "PRIVATE-TOKEN: vYGmsCuDTHiipDiD8Tn9" http://wpp.isd.dp.ua/gitlab/api/v3/projects/search/test_for_grunt | awk -F 'id":|,' '{print $2}')
## get file content
## curl -s -H "PRIVATE-TOKEN: vYGmsCuDTHiipDiD8Tn9" http://wpp.isd.dp.ua/gitlab/api/v3/projects/95/repository/blobs/develop?filepath="autotest/targetConfig.json"

cat /dev/null > $FILE
echo '{' >> $FILE
echo -e '\t"targets":' >> $FILE
echo -e '\t\t[' >> $FILE
counter=0
a=$(( ${#list_of_targets[@]} -1 ))
while (( $counter < $a ))
do
        echo -e '\t\t\t"'${list_of_targets[$counter]}'",' >> $FILE
        echo $(grep branch ${list_of_targets[$counter]}/targetConfig.json)  >> $FILE
        ((counter++))
done
if [ "$counter" -eq "$a" ]
then
        echo -e '\t\t\t"'${list_of_targets[@]:(-1)}'"' >> $FILE
        ((counter++))
fi
echo -e '\t\t]' >> $FILE
echo '}'  >> $FILE
