#!/bin/bash

TMP_FILE=lib-processorraw
cat /dev/null > $TMP_FILE
cat - > $TMP_FILE

REPONAME=lib-processor
STATUS_FILE=/home/jenkins/irls-reader-artifacts/$REPONAME-status.json

# create json file
cat /dev/null > $STATUS_FILE
echo '{' >> $STATUS_FILE
echo -e '\t"processorBranch": [' >> $STATUS_FILE
counter=1
a=$(git branch -a | sed 's/\*//g' | wc -l)
for i in $(git branch -a | sed 's/\*//g'); do
        HASHCOMMIT=$(git log -1 "$i" --pretty=format:%H)
        if [ "$counter" -eq "$a" ]
        then
                echo -e '\t\t{ "branchName":"'$i'", "hashCommit":"'$HASHCOMMIT'"}' >> $STATUS_FILE
                ((counter++))
        else
                echo -e '\t\t{ "branchName":"'$i'", "hashCommit":"'$HASHCOMMIT'" },' >> $STATUS_FILE
                ((counter++))
        fi
done
echo -e '\t]' >> $STATUS_FILE
echo '}'  >> $STATUS_FILE


BRANCH=$(cat $TMP_FILE | awk '{print $3}' | sed 's/refs\/heads\///g')

# run of job
wget -qO- --auth-no-challenge --http-user=dvac --http-password="0f64d6238d107249f79deda4d6a2f9fc" http://wpp.isd.dp.ua/jenkins/job/irls-prebuild/buildWithParameters\?token=Sheedah8\&REPONAME=$REPONAME\&BRANCH=$BRANCH &> /dev/null
wget -qO- --auth-no-challenge --http-user=dvac --http-password="0f64d6238d107249f79deda4d6a2f9fc" http://wpp.isd.dp.ua/jenkins/job/lib-processor-build/buildWithParameters\?token=Sheedah8\&BRANCHNAME=$BRANCH &> /dev/null
# email notify
cat $TMP_FILE | git-commit-notifier /usr/local/lib/ruby/gems/2.1.0/gems/git-commit-notifier-0.12.6/config/git-notifier-config
