#!/bin/bash

TMP_FILE=targetsraw
cat /dev/null > $TMP_FILE
cat - > $TMP_FILE

REPONAME=targets
BRANCH=$(cat $TMP_FILE | awk '{print $3}' | sed 's/refs\/heads\///g')

# run of job
wget -qO- --auth-no-challenge --http-user=dvac --http-password="0f64d6238d107249f79deda4d6a2f9fc" http://wpp.isd.dp.ua/jenkins/job/irls-prebuild/buildWithParameters\?token=Sheedah8\&REPONAME=$REPONAME\&BRANCH=$BRANCH &> /dev/null

# refresh list of targets
TMP_LIST_FILE=templistfile
cat /dev/null > $TMP_LIST_FILE
git diff --cached --name-only > $TMP_LIST_FILE
FILE=/home/jenkins/irls-reader-artifacts/targets.json
list=($(cat $TMP_LIST_FILE | grep "/" | awk -F "/" '{print $1}' | sort | uniq))
        cat /dev/null > $FILE
        echo '{' >> $FILE
        echo -e '\t"targets":' >> $FILE
        echo -e '\t\t[' >> $FILE
        counter=0
        a=$(( ${#list[@]} -1 ))
        while (( $counter < $a ))
        do
                echo -e '\t\t\t"'${list[$counter]}'",' >> $FILE
                ((counter++))
        done
        if [ "$counter" -eq "$a" ]
        then
                echo -e '\t\t\t"'${list[@]:(-1)}'"' >> $FILE
                ((counter++))
        fi
        echo -e '\t\t]' >> $FILE
        echo '}'  >> $FILE

# email notify
cat $TMP_FILE | git-commit-notifier /usr/local/lib/ruby/gems/2.1.0/gems/git-commit-notifier-0.12.6/config/git-notifier-config
