#!/bin/bash

# variables
REPONAME=targets
JENKINS_URL="http://wpp.isd.dp.ua/jenkins"
JENKINS_API_TOKEN="0f64d6238d107249f79deda4d6a2f9fc"
JENKINS_API_USER="dvac"
JENKINS_RUNNING_JOB=$REPONAME
GITLAB_URL="http://wpp.isd.dp.ua/gitlab"
GITLAB_API_URL="$GITLAB_URL/api/v3/projects"
GITLAB_API_TOKEN="vYGmsCuDTHiipDiD8Tn9"
FILE=/home/jenkins/irls-reader-artifacts/$REPONAME.json

# create a temporary file
TMP_FILE=$REPONAME-raw
cat /dev/null > $TMP_FILE
cat - > $TMP_FILE

# determine of next variables
BRANCH=$(cat $TMP_FILE | awk '{print $3}' | sed 's/refs\/heads\///g')
LIST_OF_TARGETS=($(git ls-tree --name-only -d $BRANCH | grep -v node_modules))
ID_OF_REPO=$(curl -s -H "PRIVATE-TOKEN: $GITLAB_API_TOKEN" $GITLAB_API_URL/search/$REPONAME | awk -F 'id":|,' '{print $2}')

# create the json-file
cat /dev/null > $FILE
echo '{' >> $FILE
echo -e '\t"targets":' >> $FILE
echo -e '\t\t[' >> $FILE
counter=0
a=$(( ${#LIST_OF_TARGETS[@]} -1 ))
while (( $counter < $a ))
do
        TARGET_BRANCH=$(curl -s -H "PRIVATE-TOKEN: $GITLAB_API_TOKEN" $GITLAB_API_URL/$ID_OF_REPO/repository/blobs/$BRANCH?filepath=${LIST_OF_TARGETS[$counter]}/targetConfig.json | grep branch | awk 'NR>1{print $1}' RS=[ FS=])
        TARGET_FACET=$(curl -s -H "PRIVATE-TOKEN: $GITLAB_API_TOKEN" $GITLAB_API_URL/$ID_OF_REPO/repository/blobs/$BRANCH?filepath=${LIST_OF_TARGETS[$counter]}/targetConfig.json | grep facet | awk -F '"' '{print $4}')
        TARGET_BRAND=$(curl -s -H "PRIVATE-TOKEN: $GITLAB_API_TOKEN" $GITLAB_API_URL/$ID_OF_REPO/repository/blobs/$BRANCH?filepath=${LIST_OF_TARGETS[$counter]}/targetConfig.json | grep brand | awk -F '"' '{print $4}')
        TARGET_PLATFORMS=$(curl -s -H "PRIVATE-TOKEN: $GITLAB_API_TOKEN" $GITLAB_API_URL/$ID_OF_REPO/repository/blobs/$BRANCH?filepath=${LIST_OF_TARGETS[$counter]}/targetConfig.json | grep platforms | awk 'NR>1{print $1}' RS=[ FS=])
        echo -e '\t\t\t{ "target_name": "'${LIST_OF_TARGETS[$counter]}'", "branch": ['$TARGET_BRANCH'], "facet": ["'$TARGET_FACET'"], "brand": ["'$TARGET_BRAND'"], "platforms": ['$TARGET_PLATFORMS'] },' >> $FILE

        ((counter++))
done
if [ "$counter" -eq "$a" ]
then
        TARGET_BRANCH=$(curl -s -H "PRIVATE-TOKEN: $GITLAB_API_TOKEN" $GITLAB_API_URL/$ID_OF_REPO/repository/blobs/$BRANCH?filepath=${LIST_OF_TARGETS[$counter]}/targetConfig.json | grep branch | awk 'NR>1{print $1}' RS=[ FS=])
        TARGET_FACET=$(curl -s -H "PRIVATE-TOKEN: $GITLAB_API_TOKEN" $GITLAB_API_URL/$ID_OF_REPO/repository/blobs/$BRANCH?filepath=${LIST_OF_TARGETS[$counter]}/targetConfig.json | grep facet | awk -F '"' '{print $4}')
        TARGET_BRAND=$(curl -s -H "PRIVATE-TOKEN: $GITLAB_API_TOKEN" $GITLAB_API_URL/$ID_OF_REPO/repository/blobs/$BRANCH?filepath=${LIST_OF_TARGETS[$counter]}/targetConfig.json | grep brand | awk -F '"' '{print $4}')
        TARGET_PLATFORMS=$(curl -s -H "PRIVATE-TOKEN: $GITLAB_API_TOKEN" $GITLAB_API_URL/$ID_OF_REPO/repository/blobs/$BRANCH?filepath=${LIST_OF_TARGETS[$counter]}/targetConfig.json | grep platforms | awk 'NR>1{print $1}' RS=[ FS=])
        echo -e '\t\t\t{ "target_name": "'${LIST_OF_TARGETS[$counter]}'", "branch": ['$TARGET_BRANCH'], "facet": ["'$TARGET_FACET'"], "brand": ["'$TARGET_BRAND'"], "platforms": ['$TARGET_PLATFORMS'] }' >> $FILE
        ((counter++))
fi
echo -e '\t\t]' >> $FILE
echo '}'  >> $FILE

# run of jenkins job
curl -s -H "PRIVATE-TOKEN: $JENKINS_API_TOKEN" $JENKINS_URL/job/$JENKINS_RUNNING_JOB/buildWithParameters\?token=Sheedah8\&REPONAME=$REPONAME\&BRANCH=$BRANCH

# email notify
cat $TMP_FILE | /usr/local/bin/git-commit-notifier /usr/local/lib/ruby/gems/2.1.0/gems/git-commit-notifier-0.12.10/config/git-notifier-config.yml
